services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80" # משйיך לפורט 8080 כדי להימנע מבעיות הרשאות במק
    restart: always